In [2]:
import tensorflow as tf
import numpy as np

In [3]:
# Hyperparams

width = 5
height = 5
lines = 10
depth = 1

In [4]:
frame = np.zeros([depth, height, width])
frame[0,0,0] = 1
frame[0,1,1] = 1
print frame
frame = np.zeros([depth, height, width])

[[[ 1.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]]


In [5]:
print frame
for i in range(2):
    for a in range(2):
        print frame
        frame[depth-1,i,a] = 1
        depth += 1
        #frame = np.append(frame,np.zeros([height, width]))
        print frame
        frame = frame.reshape(depth, height, width)

[[[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]]
[[[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]]
[[[ 1.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]]


ValueError: cannot reshape array of size 25 into shape (2,5,5)